set ts=4
set expandtab

" open launch files as xml
filetype on
au BufNewFile,BufRead *.launch set filetype=xml

" This should already be in /etc/vim/vimrc
" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

